# Port Server
quarkus.http.port=8081

# Database Configuration (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=502091

# Reactive URL (Untuk Hibernate Reactive / Panache)
quarkus.datasource.reactive.url=postgresql://localhost:5432/user_service

# JDBC URL
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/user_service

# Flyway Migration Configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# Hibernate ORM Configuration
quarkus.hibernate-orm.log.sql=true

# SmallRye JWT Configuration
mp.jwt.verify.issuer=https://omnichannel.ari.com/issuer
smallrye.jwt.new-token.lifespan=28800

# Mengambil lokasi Private & Public Key dari Environment Variable
# Jika Env Var tidak ada, baru fallback ke lokasi default di classpath
smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION:jwt/privateKey.pem}
mp.jwt.verify.publickey.location=${JWT_VERIFY_KEY_LOCATION:jwt/publicKey.pem}